name: Daily Checkpoint

on:
  schedule:
    - cron: '20 16 * * *'  # Запуск в 4:20 PM каждый день (UTC)

jobs:
  create_checkpoint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Get current timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Create Bitcoin genesis checkpoint
      run: |
        python datm/blockchain.py create_checkpoint "bitcoin" ${{ env.TIMESTAMP }}

    - name: Create Ethereum genesis checkpoint
      run: |
        python datm/blockchain.py create_checkpoint "ethereum" ${{ env.TIMESTAMP }}

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Daily checkpoint ${{ env.TIMESTAMP }}"
        git push
