name: Daily Checkpoint

on:
  schedule:
    - cron: '20 4 * * *'  # Run every day at 4:20 PM (UTC)
  workflow_dispatch:  # Enables manual triggering

jobs:
  create_checkpoint:
    runs-on: ubuntu-latest
    steps:

    # Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # Official Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5.2.0

    # Install dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Get current timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Create Blockchain Test genesis checkpoint
      run: |
        python bitcoinlib.py
        
    - name: Check for changes
      run: |
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes to commit."
          exit 0
        else
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Daily checkpoint ${{ env.TIMESTAMP }}"
          git push
        fi
